### ISSUE TITLE
go migration TODO list

### ISSUE THREAD

**Issue by bourdakos1** [cloud-annotations/training#164]
### API
- [x] WML API
   - https://github.com/cloud-annotations/training/blob/master/src/api/api.js
   - https://github.com/cloud-annotations/training/blob/master/src/api/wml.js
- [x] COS API (https://github.com/IBM/ibm-cos-sdk-go)
- [x] IBM Cloud login API
- [x] Websockets

##### Login:
- [x] login
- [x] logout
##### main:
- [x] list
- [x] train
##### During training:
- [x] logs
- [x] progress
- [ ] tensorboard
- [ ] cancel
##### Post training:
- [ ] ~deploy~
- [x] download
##### CLI util:
- [ ] update

### UI Components
- [x] table (https://github.com/gosuri/uitable) (https://github.com/olekukonko/tablewriter)
- [x] loading (https://github.com/briandowns/spinner)
- [x] progress bar (https://github.com/cheggaaa/pb) (https://github.com/gosuri/uiprogress)
- [x] standard text input

### Login
- [x] support for no UI login

----
```
global flags:
  [--non-interactive]
  [--cos <file>]
  [--wml <file>]

cacli login

cacli logout

cacli list

cacli train [<bucket>]
  [--output <bucket>]
  [--steps <steps>]
  [--gpu <k80|v100|v100x2>]
  [--script <file>]
  [--pipeline-config <file>] // only works for object detection and non-custom script
  [--checkpoint <file>] // only works for object detection and non-custom script
  // maybe instead we have more prebuilt scripts.zips?

cacli logs <model-id>

cacli progress <model-id>

cacli tensorboard <model-id>

cacli cancel <model-id>

cacli deploy <model-id>

cacli download <model-id>
  [--tfjs]
  [--coreml]
  [--tflite]

cacli update
```

**Comment by bourdakos1** [comment]
TODO grep

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/download.go
  35,2: 	// TODO: update usage for all commands that require a model id

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/list/list.go
  12,2: 	// TODO: needs to be sorted, also might have a date bug, said was 5 hours ago but was probably 5 min

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/login/assertLoggedIn.go
  26,2: 	// TODO: use some sort of global config for this path.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/login/login.go
  214,2: 	// TODO: clean this.
  258,1: // TODO: theoretical login examples:
  335,1: // TODO: easily switch instances without re-login

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/logout/logout.go
  21,2: 	// TODO: use some sort of global config for this path.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/logs/logs.go
  28,3: 		// TODO: pull from object storage.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/train/train.go
  51,3: 		// TODO: allow passing path to training zip.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/ibmcloud/cloud.go
  42,1: // TODO: logical timeout, 10 seconds wasn't long enough.
  47,1: // TODO: We need to check the response for errors.
  48,1: // TODO: return interface instead of side effects.
  220,1: // TODO: better way to pass url encoded params.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/ibmcloud/wrapper.go
  30,1: // TODO: make a helper function for loading in config files.
  175,3: 		// TODO: get the rest of the accounts.
  203,3: 		// TODO: get the rest of the resources.
  215,3: 		// TODO: get the rest of the resources.
  227,3: 		// TODO: this should normally only ever return 1, but we should still get
  248,2: 	// TODO: look into actual url from regionID
  353,3: 		// TODO: get actual version.
  378,2: 	// TODO: cache the credentials.
  422,2: 	// TODO: look into actual url from regionID
  438,2: 	// TODO: look into actual url from regionID

**Comment by bourdakos1** [comment]
/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/login/assertLoggedIn.go
  26,2: 	// TODO: use some sort of global config for this path.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/login/login.go
  214,2: 	// TODO: clean this.
  258,1: // TODO: theoretical login examples:
  335,1: // TODO: easily switch instances without re-login

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/logout/logout.go
  21,2: 	// TODO: use some sort of global config for this path.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/logs/logs.go
  29,3: 		// TODO: pull from object storage.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/progress/progress.go
  106,2: 	// TODO: we need to break when this finishes...
  153,4: 			// TODO: wipe bar and start checking for new regex

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/cmd/train/train.go
  65,3: 		// TODO: allow passing path to training zip.
  66,3: 		// TODO: allow project name and output bucket.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/ibmcloud/cloud.go
  42,1: // TODO: logical timeout, 10 seconds wasn't long enough.
  47,1: // TODO: We need to check the response for errors.
  48,1: // TODO: return interface instead of side effects.
  220,1: // TODO: better way to pass url encoded params.

/Users/niko/go/src/github.com/cloud-annotations/training/cacli/ibmcloud/wrapper.go
  28,1: // TODO: make a helper function for loading in config files.
  173,3: 		// TODO: get the rest of the accounts.
  201,3: 		// TODO: get the rest of the resources.
  213,3: 		// TODO: get the rest of the resources.
  225,3: 		// TODO: this should normally only ever return 1, but we should still get
  246,2: 	// TODO: look into actual url from regionID
  250,2: 	// TODO: we shouldn't use a magic number.
  358,3: 		// TODO: get actual version of the github training.zip release.
  383,2: 	// TODO: cache the HMAC credentials.
  427,2: 	// TODO: look into actual url from regionID
  443,2: 	// TODO: look into actual url from regionID
  547,1: // TODO: listen for close()

**Comment by bourdakos1** [comment]
@moficodes is an `update` command a common pattern for updating a CLI? i.e. `cacli update` would update cacli to the latest version. 

How would we go about doing this?

**Comment by bourdakos1** [comment]
## Poll:
#### Should `bootstrap` and `export` be deprecated? 
`bootstrap` uploads a folder to COS
`export` downloads a bucket from COS
 
> Both of these tasks should be easily achievable with the standard s3 CLI

# `👍 Deprecate it` `👎 Keep it`

**Comment by bourdakos1** [comment]
MVP TODO

#### cmd/logs/logs.go
- [ ] pull from object storage

#### cmd/train/train.go
- [ ] allow output bucket

#### ibmcloud/cloud.go
- [ ] We need to check the response for errors

#### ibmcloud/wrapper.go
- [ ] load entire list of resources / accounts / [credentials].
- [ ] look into actual url from regionID
- [ ] get actual version of the github training.zip release.

**Comment by bourdakos1** [comment]
Beta release TODO
bug-fixes:
- [ ] get object
- [ ] download dir
- [ ] the bucket not being listed does not mean the bucket doesn't exist

ui:
- [ ] descriptions for --help

**Comment by bourdakos1** [comment]
Golang CLI is now master 🎉 Closing this and opening issues for remaining work
